#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
ifconfig_ofif (){
    ifconfig | grep $1 -A1 | tail -n1 | grep "inet" | cut -d ' ' -f 2
}

alias ipy="python -c 'import IPython; IPython.terminal.ipapp.launch_new_instance()'"
alias less="vimpager"

test -e "${HOME}/.iterm2_shell_integration.zsh" \
    && source "${HOME}/.iterm2_shell_integration.zsh"

alias vi="nvim"

# Open (current) git repository's remote in the browser
git-remote-open(){
    # Parse remote and branch as parameter or get default
    remote=`git remote | head -n 1`
    remote=${1-$remote}
    branch=`git rev-parse --abbrev-ref HEAD`
    branch=${2-$branch}

    # Get remote URL and strip .git suffix
    baseurl=`git remote get-url $remote`
    baseurl=${baseurl%".git"}

    # Convert SSH URLs to HTTPS URLs
    if [[ $baseurl = "git@"* ]]; then
        baseurl=${baseurl//://}
        baseurl=${baseurl//git@/https://}
    fi

    # Build repository URL
    if [[ ( $baseurl = *"github.com"* ) || ( $baseurl = *"gitlab.com"* ) ]];
    then
        url=$baseurl/tree/$branch
    elif [[ $baseurl = *"visualstudio.com"* ]]; then
        url=$baseurl/?version=GB$branch
    fi

    echo "$url"

    # Open URL using browser
    if [[ $OSTYPE = "darwin"* ]]; then
        open $url
    elif [[ $OSTYPE = "msys" ]]; then
        start $url
    fi
}
