# Enable menu driven completion
zstyle ':completion:*' menu select
# Enable case-insensitive completion
zstyle ':completion:*' matcher-list 'm:{a-zA-Z}={A-Za-z}'
# Enable autocompletion for SSH hosts and logins
zstyle ':completion:*:ssh:*' hosts
zstyle ':completion:*:slogin:*' hosts

# Set up additional paths
paths+=('~/.npm-global/bin')

# Set up fzf
source /usr/share/doc/fzf/examples/key-bindings.zsh
source /usr/share/doc/fzf/examples/completion.zsh

### Zplugin configuration
###

# Zplugin setup
source ~/.zinit/bin/zinit.zsh

# Autosuggestions & fast-syntax-highlighting
zinit ice wait lucid atinit"ZINIT[COMPINIT_OPTS]=-C; zpcompinit; zpcdreplay"
zinit light zdharma/fast-syntax-highlighting

# zsh-autosuggestions
zinit ice wait lucid atload"!_zsh_autosuggest_start"
zinit light zsh-users/zsh-autosuggestions

# zsh-completions
zinit ice wait lucid blockf atpull"zinit creinstall -q ."
zinit light zsh-users/zsh-completions

# sharkdp/bat
zinit ice as"command" from"gh-r" mv"bat* -> bat" pick"bat/bat"
zinit light sharkdp/bat

# ogham/exa, replacement for ls
zinit ice wait lucid from"gh-r" as"program" mv"bin/exa* -> exa"
zinit light ogham/exa

# set exa aliases
zinit light DarrinTisdale/zsh-aliases-exa

# sharkdp/fd
zinit ice as"program" from"gh-r" mv"fd* -> fd" pick"fd/fd"
zinit light sharkdp/fd

# BurntSushi/ripgrep
zinit ice as"program" from"gh-r" mv"ripgrep* -> rg" pick "rg/rg"
zinit light BurntSushi/ripgrep

# sorin-ionescu/prezto/modules/history
zinit ice svn
zinit snippet PZT::modules/history

# zdharma/history-search-multi-word
zstyle ":history-search-multi-word" page-size "11"
zinit ice wait lucid
zinit light zdharma/history-search-multi-word

# set prompt theme
zinit ice from="gh-r" as"program" atload'eval "$(starship init zsh)"'
zinit load starship/starship

# ryutok/rust-zsh-completions
zinit light ryutok/rust-zsh-completions

### End zplugin configuration
###

# Enable completion
autoload -Uz compinit
compinit

### Functions
###

# Load identities
function ssh-identity-load() {
	 zstyle ':prezto:module:ssh:load' identities 'id_nevin_github'
	 zinit ice svn
	 zinit snippet PZT::modules/ssh
}

# Source ROS Noetic
function source-ros-noetic() {
	 source /opt/ros/noetic/setup.zsh
}

# Source ROS Foxy
function source-ros-foxy() {
	 source /opt/ros/foxy/setup.zsh
}

### End functions
###
